services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - n8n_n8n-net  # Docker Compose stellt Projektnamen meist davor

networks:
  n8n_n8n-net:
    external: true

volumes:
  ollama:
    external: true
    name: ollama
    
    